### PR TITLE
Added Aho-Corasick Algorithm for Pattern Searching in Search Algorithms

### PR DESCRIPTION
**Pull request by jay13makhija**
**Fixes issue:**

#397 

**Changes:**

### CODE REVIEW

**Comment by jay13makhija** [comment]
Please Merge this request

**Comment by Princeton21** [comment]
Kindly mention the issue number you have worked on in the above comment

**Review by Princeton21 — CHANGES_REQUESTED** [review]
Kindly create a sub-folder [here](https://github.com/Princeton21/Data-Structures-and-Algorithms/tree/0eecb7045250453720181f30e25f779ab0dacd26/Code/string_algorithms)
for the algorithm.
and add a README.md file describing about the algorithm with the pseudo-code.

**Comment by Princeton21** [comment]
@jay13makhija are you still working on this PR?

**Pull request closed without merging**
