### PR TITLE
Storing and retrieval in an array

### PR DESCRIPTION
**Pull request by Nupurgit2000**
**Fixes issue:**

#237

**Changes:**

This is a program for storing and retrieval elements in an array in C.

### CODE REVIEW

**Comment by Nupurgit2000** [comment]
Thank You

**Comment by Nupurgit2000** [comment]
Hey, why this is showing on my profile that this project has been excluded and what to do now?

**Comment by Princeton21** [comment]
@Nupurgit2000 The PR's you and everyone have made are beginner friendly.
So this repository got excluded as PR's should've been meaningful.

Nevermind I hope that the efforts made by everyone may motivate them to make meaningful open source contributions.

**Comment by Nupurgit2000** [comment]
Okay, thanks for replying.

**Pull request merged**
